package com.resumeai.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.resumeai.dto.InterviewKbDocItem;
import com.resumeai.dto.InterviewKbLlmImportRequest;
import com.resumeai.dto.InterviewKbLlmImportResponse;
import com.resumeai.model.UserAccount;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Pattern;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

@Service
public class InterviewKbLlmImportService {
    private static final int DEFAULT_QUESTION_COUNT = 30;
    private static final int MAX_GENERATED_CANDIDATES = 220;
    private static final Pattern SPLIT_LINES = Pattern.compile("[\\n\\r]+");
    private static final Pattern SPLIT_SENTENCE = Pattern.compile("[。！？!?;；]+");
    private static final Pattern PREFIX = Pattern.compile("^[\\s\\-•·●◆◇\\d一二三四五六七八九十①②③④⑤⑥⑦⑧⑨⑩()（）【】\\[\\].、,:：]+");
    private static final DateTimeFormatter TITLE_TIME_FORMAT =
            DateTimeFormatter.ofPattern("yyyyMMddHHmm", Locale.ROOT).withZone(ZoneId.of("Asia/Shanghai"));

    private final WebClient.Builder webClientBuilder;
    private final ObjectMapper objectMapper;
    private final InterviewQuestionKbService interviewQuestionKbService;
    private final ConfigService configService;

    public InterviewKbLlmImportService(
            WebClient.Builder webClientBuilder,
            ObjectMapper objectMapper,
            InterviewQuestionKbService interviewQuestionKbService,
            ConfigService configService) {
        this.webClientBuilder = webClientBuilder;
        this.objectMapper = objectMapper;
        this.interviewQuestionKbService = interviewQuestionKbService;
        this.configService = configService;
    }

    public InterviewKbLlmImportResponse importByLlm(InterviewKbLlmImportRequest req, UserAccount admin) {
        String topic = clean(req.getTopic());
        String baseUrl = clean(req.getBaseUrl());
        String apiKey = clean(req.getApiKey());
        String model = clean(req.getModel());
        if (baseUrl.isEmpty()) {
            throw new IllegalArgumentException("llm_base_url is required");
        }
        if (apiKey.isEmpty()) {
            throw new IllegalArgumentException("llm_api_key is required");
        }
        if (model.isEmpty()) {
            model = clean(configService.getEntity().getModel());
        }
        if (model.isEmpty()) {
            model = "gpt-5.3-codex";
        }
        int requestedCount = normalizeQuestionCount(req.getQuestionCount());

        String content = requestModel(topic, requestedCount, baseUrl, apiKey, model);
        List<String> questions = extractQuestions(content, requestedCount);
        if (questions.isEmpty()) {
            throw new IllegalArgumentException("no interview questions generated by model");
        }

        String title = clean(req.getTitle());
        if (title.isEmpty()) {
            title = "模型题库-" + topic + "-" + TITLE_TIME_FORMAT.format(Instant.now());
        }
        String filename = "llm_" + topicToFilePart(topic) + "_" + Instant.now().toEpochMilli() + ".txt";
        InterviewKbDocItem doc = interviewQuestionKbService.importQuestions(questions, title, filename, admin);

        InterviewKbLlmImportResponse response = new InterviewKbLlmImportResponse();
        response.setTopic(topic);
        response.setModel(model);
        response.setRequestedCount(requestedCount);
        response.setGeneratedCount(questions.size());
        response.setImportedCount(doc.getQuestionCount() == null ? 0 : doc.getQuestionCount());
        response.setDoc(doc);
        return response;
    }

    private String requestModel(String topic, int count, String baseUrl, String apiKey, String model) {
        String prompt = """
                你是资深面试官，请基于主题生成高质量面试题。
                主题：%s
                数量：%d

                约束：
                1. 覆盖基础、进阶、架构、实战排障四个层次。
                2. 问题要具体，不要空泛，不要重复。
                3. 输出仅 JSON，格式：
                {
                  "questions": ["问题1", "问题2"]
                }
                """.formatted(topic, count);

        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("model", model);
        payload.put("temperature", 0.4);
        payload.put("messages", List.of(
                Map.of("role", "system", "content", "You are an interview question generator. Return strict JSON."),
                Map.of("role", "user", "content", prompt)
        ));

        try {
            WebClient client = webClientBuilder
                    .baseUrl(normalizeBaseUrl(baseUrl))
                    .defaultHeader(HttpHeaders.AUTHORIZATION, "Bearer " + apiKey)
                    .build();
            JsonNode resp = client.post()
                    .uri("/chat/completions")
                    .contentType(MediaType.APPLICATION_JSON)
                    .bodyValue(payload)
                    .retrieve()
                    .bodyToMono(JsonNode.class)
                    .block(Duration.ofSeconds(70));
            if (resp == null) {
                throw new IllegalArgumentException("llm response is empty");
            }
            String content = resp.path("choices").path(0).path("message").path("content").asText("");
            if (content.isBlank()) {
                throw new IllegalArgumentException("llm response is empty");
            }
            return content;
        } catch (IllegalArgumentException ex) {
            throw ex;
        } catch (Exception ex) {
            throw new IllegalArgumentException("llm request failed");
        }
    }

    private List<String> extractQuestions(String content, int requestedCount) {
        List<String> fromJson = parseQuestionsFromJson(content);
        if (!fromJson.isEmpty()) {
            return fromJson.stream().limit(requestedCount).toList();
        }
        return parseQuestionsFromPlainText(content, requestedCount);
    }

    private List<String> parseQuestionsFromJson(String content) {
        String raw = clean(content);
        if (raw.isEmpty()) {
            return List.of();
        }
        try {
            JsonNode root = objectMapper.readTree(trimToJson(raw));
            JsonNode q = root.path("questions");
            if (!q.isArray()) {
                return List.of();
            }
            LinkedHashSet<String> out = new LinkedHashSet<>();
            for (JsonNode item : q) {
                String normalized = normalizeQuestion(item.asText(""));
                if (!normalized.isEmpty()) {
                    out.add(normalized);
                }
                if (out.size() >= MAX_GENERATED_CANDIDATES) {
                    break;
                }
            }
            return new ArrayList<>(out);
        } catch (Exception ex) {
            return List.of();
        }
    }

    private List<String> parseQuestionsFromPlainText(String content, int requestedCount) {
        LinkedHashSet<String> out = new LinkedHashSet<>();
        for (String line : SPLIT_LINES.split(clean(content))) {
            String normalized = normalizeQuestion(line);
            if (!normalized.isEmpty()) {
                out.add(normalized);
            }
            if (out.size() >= requestedCount) {
                break;
            }
        }
        if (out.size() >= requestedCount) {
            return new ArrayList<>(out);
        }
        for (String sentence : SPLIT_SENTENCE.split(clean(content))) {
            String normalized = normalizeQuestion(sentence);
            if (!normalized.isEmpty()) {
                out.add(normalized);
            }
            if (out.size() >= requestedCount) {
                break;
            }
        }
        return new ArrayList<>(out);
    }

    private String normalizeQuestion(String input) {
        String text = clean(input);
        if (text.isEmpty()) {
            return "";
        }
        text = PREFIX.matcher(text).replaceFirst("");
        text = text.replaceAll("\\s+", " ").trim();
        text = text.replace(';', '，').replace('；', '，');
        text = text.replaceAll("^[,，。;；:：]+|[,，。;；:：]+$", "").trim();
        if (text.length() < 6) {
            return "";
        }
        if (text.length() > 240) {
            text = text.substring(0, 240).trim();
        }
        boolean hasQ = text.contains("?") || text.contains("？");
        if (!hasQ) {
            if (containsChinese(text)) {
                text = text + "？";
            } else {
                text = text + "?";
            }
        }
        return text;
    }

    private String trimToJson(String raw) {
        String text = clean(raw);
        int start = text.indexOf('{');
        int end = text.lastIndexOf('}');
        if (start >= 0 && end > start) {
            return text.substring(start, end + 1);
        }
        return text;
    }

    private int normalizeQuestionCount(Integer count) {
        int value = count == null ? DEFAULT_QUESTION_COUNT : count;
        if (value < 5) {
            value = 5;
        }
        if (value > 120) {
            value = 120;
        }
        return value;
    }

    private String topicToFilePart(String topic) {
        String part = topic.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9\\u4e00-\\u9fff]+", "_");
        if (part.isBlank()) {
            return "topic";
        }
        if (part.length() > 60) {
            return part.substring(0, 60);
        }
        return part;
    }

    private String normalizeBaseUrl(String baseUrl) {
        String url = clean(baseUrl);
        if (url.isEmpty()) {
            return "https://api.openai.com/v1";
        }
        if (url.endsWith("/")) {
            url = url.substring(0, url.length() - 1);
        }
        if (url.matches("^https?://[^/]+$")) {
            return url + "/v1";
        }
        return url;
    }

    private boolean containsChinese(String text) {
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (c >= '\u4e00' && c <= '\u9fff') {
                return true;
            }
        }
        return false;
    }

    private String clean(String value) {
        return value == null ? "" : value.trim();
    }
}
