package com.resumeai.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.resumeai.dto.InterviewKbDocItem;
import com.resumeai.dto.InterviewKbLlmImportRequest;
import com.resumeai.dto.InterviewKbLlmImportResponse;
import com.resumeai.model.UserAccount;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Pattern;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

/**
 * 通过大语言模型（LLM）自动生成面试题并导入题库的服务。
 * 流程：构造 prompt -> 调用 LLM 接口 -> 解析返回内容 -> 去重/规范化 -> 写入题库。
 */
@Service
public class InterviewKbLlmImportService {
    // 默认生成题目数量
    private static final int DEFAULT_QUESTION_COUNT = 30;
    // 单次最大候选题目上限，防止解析过多
    private static final int MAX_GENERATED_CANDIDATES = 220;
    // 按行拆分的正则
    private static final Pattern SPLIT_LINES = Pattern.compile("[\\n\\r]+");
    // 按句号/问号等拆分的正则
    private static final Pattern SPLIT_SENTENCE = Pattern.compile("[。！？!?;；]+");
    // 去除题目序号前缀的正则
    private static final Pattern PREFIX = Pattern.compile("^[\\s\\-•·●◆◇\\d一二三四五六七八九十①②③④⑤⑥⑦⑧⑨⑩()（）【】\\[\\].、,:：]+");
    // 文档标题中的时间格式
    private static final DateTimeFormatter TITLE_TIME_FORMAT =
            DateTimeFormatter.ofPattern("yyyyMMddHHmm", Locale.ROOT).withZone(ZoneId.of("Asia/Shanghai"));

    private final WebClient.Builder webClientBuilder;
    private final ObjectMapper objectMapper;
    private final InterviewQuestionKbService interviewQuestionKbService;
    private final ConfigService configService;

    public InterviewKbLlmImportService(
            WebClient.Builder webClientBuilder,
            ObjectMapper objectMapper,
            InterviewQuestionKbService interviewQuestionKbService,
            ConfigService configService) {
        this.webClientBuilder = webClientBuilder;
        this.objectMapper = objectMapper;
        this.interviewQuestionKbService = interviewQuestionKbService;
        this.configService = configService;
    }

    /**
     * 通过 LLM 生成面试题并导入题库。
     * 校验参数 -> 调用模型 -> 提取题目 -> 导入题库 -> 返回统计结果。
     */
    public InterviewKbLlmImportResponse importByLlm(InterviewKbLlmImportRequest req, UserAccount admin) {
        String topic = clean(req.getTopic());
        String baseUrl = clean(req.getBaseUrl());
        String apiKey = clean(req.getApiKey());
        String model = clean(req.getModel());
        if (baseUrl.isEmpty()) {
            throw new IllegalArgumentException("llm_base_url is required");
        }
        if (apiKey.isEmpty()) {
            throw new IllegalArgumentException("llm_api_key is required");
        }
        // 模型为空时依次尝试全局配置和硬编码默认值
        if (model.isEmpty()) {
            model = clean(configService.getEntity().getModel());
        }
        if (model.isEmpty()) {
            model = "gpt-5.3-codex";
        }
        int requestedCount = normalizeQuestionCount(req.getQuestionCount());

        // 调用 LLM 获取原始内容
        String content = requestModel(topic, requestedCount, baseUrl, apiKey, model);
        // 从返回内容中提取面试题
        List<String> questions = extractQuestions(content, requestedCount);
        if (questions.isEmpty()) {
            throw new IllegalArgumentException("no interview questions generated by model");
        }

        // 生成文档标题和文件名
        String title = clean(req.getTitle());
        if (title.isEmpty()) {
            title = "模型题库-" + topic + "-" + TITLE_TIME_FORMAT.format(Instant.now());
        }
        String filename = "llm_" + topicToFilePart(topic) + "_" + Instant.now().toEpochMilli() + ".txt";
        // 导入题库
        InterviewKbDocItem doc = interviewQuestionKbService.importQuestions(questions, title, filename, admin);

        // 组装响应
        InterviewKbLlmImportResponse response = new InterviewKbLlmImportResponse();
        response.setTopic(topic);
        response.setModel(model);
        response.setRequestedCount(requestedCount);
        response.setGeneratedCount(questions.size());
        response.setImportedCount(doc.getQuestionCount() == null ? 0 : doc.getQuestionCount());
        response.setDoc(doc);
        return response;
    }

    /**
     * 调用 LLM 的 chat/completions 接口生成面试题。
     * 构造 prompt 要求模型返回 JSON 格式的题目列表。
     */
    private String requestModel(String topic, int count, String baseUrl, String apiKey, String model) {
        String prompt = """
                你是资深面试官，请基于主题生成高质量面试题。
                主题：%s
                数量：%d

                约束：
                1. 覆盖基础、进阶、架构、实战排障四个层次。
                2. 问题要具体，不要空泛，不要重复。
                3. 输出仅 JSON，格式：
                {
                  "questions": ["问题1", "问题2"]
                }
                """.formatted(topic, count);

        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("model", model);
        payload.put("temperature", 0.4);
        payload.put("messages", List.of(
                Map.of("role", "system", "content", "You are an interview question generator. Return strict JSON."),
                Map.of("role", "user", "content", prompt)
        ));

        try {
            WebClient client = webClientBuilder
                    .baseUrl(normalizeBaseUrl(baseUrl))
                    .defaultHeader(HttpHeaders.AUTHORIZATION, "Bearer " + apiKey)
                    .build();
            JsonNode resp = client.post()
                    .uri("/chat/completions")
                    .contentType(MediaType.APPLICATION_JSON)
                    .bodyValue(payload)
                    .retrieve()
                    .bodyToMono(JsonNode.class)
                    .block(Duration.ofSeconds(70));
            if (resp == null) {
                throw new IllegalArgumentException("llm response is empty");
            }
            // 从标准 OpenAI 格式中提取 content 字段
            String content = resp.path("choices").path(0).path("message").path("content").asText("");
            if (content.isBlank()) {
                throw new IllegalArgumentException("llm response is empty");
            }
            return content;
        } catch (IllegalArgumentException ex) {
            throw ex;
        } catch (Exception ex) {
            throw new IllegalArgumentException("llm request failed");
        }
    }

    /**
     * 从 LLM 返回内容中提取面试题列表。
     * 优先尝试 JSON 解析，失败则回退到纯文本按行/按句拆分。
     */
    private List<String> extractQuestions(String content, int requestedCount) {
        List<String> fromJson = parseQuestionsFromJson(content);
        if (!fromJson.isEmpty()) {
            return fromJson.stream().limit(requestedCount).toList();
        }
        return parseQuestionsFromPlainText(content, requestedCount);
    }

    /** 尝试将内容作为 JSON 解析，提取 questions 数组中的题目 */
    private List<String> parseQuestionsFromJson(String content) {
        String raw = clean(content);
        if (raw.isEmpty()) {
            return List.of();
        }
        try {
            // 截取 JSON 对象部分（去除 markdown 代码块等包裹）
            JsonNode root = objectMapper.readTree(trimToJson(raw));
            JsonNode q = root.path("questions");
            if (!q.isArray()) {
                return List.of();
            }
            LinkedHashSet<String> out = new LinkedHashSet<>();
            for (JsonNode item : q) {
                String normalized = normalizeQuestion(item.asText(""));
                if (!normalized.isEmpty()) {
                    out.add(normalized);
                }
                if (out.size() >= MAX_GENERATED_CANDIDATES) {
                    break;
                }
            }
            return new ArrayList<>(out);
        } catch (Exception ex) {
            return List.of();
        }
    }

    /**
     * 纯文本模式提取面试题。
     * 先按行拆分，不够数量再按句拆分补充。
     */
    private List<String> parseQuestionsFromPlainText(String content, int requestedCount) {
        LinkedHashSet<String> out = new LinkedHashSet<>();
        // 第一轮：按行拆分
        for (String line : SPLIT_LINES.split(clean(content))) {
            String normalized = normalizeQuestion(line);
            if (!normalized.isEmpty()) {
                out.add(normalized);
            }
            if (out.size() >= requestedCount) {
                break;
            }
        }
        if (out.size() >= requestedCount) {
            return new ArrayList<>(out);
        }
        // 第二轮：按句拆分补充
        for (String sentence : SPLIT_SENTENCE.split(clean(content))) {
            String normalized = normalizeQuestion(sentence);
            if (!normalized.isEmpty()) {
                out.add(normalized);
            }
            if (out.size() >= requestedCount) {
                break;
            }
        }
        return new ArrayList<>(out);
    }

    /**
     * 规范化单条面试题文本：
     * 去前缀序号 -> 合并空白 -> 替换分号 -> 去首尾标点 -> 长度校验 -> 补问号
     */
    private String normalizeQuestion(String input) {
        String text = clean(input);
        if (text.isEmpty()) {
            return "";
        }
        text = PREFIX.matcher(text).replaceFirst("");
        text = text.replaceAll("\\s+", " ").trim();
        text = text.replace(';', '，').replace('；', '，');
        text = text.replaceAll("^[,，。;；:：]+|[,，。;；:：]+$", "").trim();
        // 过短的文本不视为有效题目
        if (text.length() < 6) {
            return "";
        }
        // 过长则截断
        if (text.length() > 240) {
            text = text.substring(0, 240).trim();
        }
        // 若不含问号则自动补充
        boolean hasQ = text.contains("?") || text.contains("？");
        if (!hasQ) {
            if (containsChinese(text)) {
                text = text + "？";
            } else {
                text = text + "?";
            }
        }
        return text;
    }

    /** 从原始文本中截取第一个 JSON 对象（花括号包裹的部分） */
    private String trimToJson(String raw) {
        String text = clean(raw);
        int start = text.indexOf('{');
        int end = text.lastIndexOf('}');
        if (start >= 0 && end > start) {
            return text.substring(start, end + 1);
        }
        return text;
    }

    /** 规范化题目数量：限制在 [5, 120] 范围内 */
    private int normalizeQuestionCount(Integer count) {
        int value = count == null ? DEFAULT_QUESTION_COUNT : count;
        if (value < 5) {
            value = 5;
        }
        if (value > 120) {
            value = 120;
        }
        return value;
    }

    /** 将主题转换为安全的文件名片段（仅保留字母数字和中文） */
    private String topicToFilePart(String topic) {
        String part = topic.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9\\u4e00-\\u9fff]+", "_");
        if (part.isBlank()) {
            return "topic";
        }
        if (part.length() > 60) {
            return part.substring(0, 60);
        }
        return part;
    }

    /** 规范化 LLM 接口的 baseUrl：去尾斜杠，纯域名时自动追加 /v1 */
    private String normalizeBaseUrl(String baseUrl) {
        String url = clean(baseUrl);
        if (url.isEmpty()) {
            return "https://api.openai.com/v1";
        }
        if (url.endsWith("/")) {
            url = url.substring(0, url.length() - 1);
        }
        // 仅有协议+域名时自动追加 /v1 路径
        if (url.matches("^https?://[^/]+$")) {
            return url + "/v1";
        }
        return url;
    }

    /** 判断文本中是否包含中文字符 */
    private boolean containsChinese(String text) {
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (c >= '\u4e00' && c <= '\u9fff') {
                return true;
            }
        }
        return false;
    }

    /** 清理字符串：null 转空串并去除首尾空白 */
    private String clean(String value) {
        return value == null ? "" : value.trim();
    }
}
